Description of test_lqr_fh
Home > examples > test_lqr_fh.m
test_lqr_fh
PURPOSE
Demo script: Test numerical solution of finite horizon linear-quadratic regulator problem in continuous time.
SYNOPSIS
This is a script file.
DESCRIPTION
 Demo script: Test numerical solution of finite horizon linear-quadratic regulator problem in continuous time.
CROSS-REFERENCE INFORMATION
This function calls:
l_quadratic_fh Finite horizon quadratic cost function.
f_linear Linear dynamics function.
f_linear Linear dynamics function.
model_linear Simple linear model, with two state dimensions, one control dimension.
model_linear Simple linear model, with two state dimensions, one control dimension.
lqr_fh Solve Riccati equation and compute optimal gains for finite horizon linear-quadratic regulator problem in continuous time.
plot_lq_fh Function for plotting solutions to the finite horizon LQ problem from the demo scripts
simulate_feedback_time_indexed Simulate trajectory using Euler integration under closed-loop, time-indexed policy control, in continuous time
evaluate_trajectory_cost_fh Function for evaluating the cost along a trajectory under a given cost function
This function is called by:
SOURCE CODE
% Demo script: Test numerical solution of finite horizon linear-quadratic regulator problem in continuous time.
clear all;
% set up numerical simulation
dt = 0.02;       % time step
N  = 200;        % number of time steps
t  = (0:N-1)*dt; % sample times
% simulation parameters
ps = []; ps.N = N; ps.dt = dt; ps.solver = 'euler';
% start state
x0 = [1;0];
% dynamics
model = model_linear; %
f = @(x, u) f_linear (x, u, model);
% cost
pc = [];
% terminal state cost
pc.QT = [1  0;  0  0.1];
% state cost
pc.Q  = pc.QT;
% command cost
pc.R  = .1;
l  = @(x,u,t) l_quadratic_fh (x, u, t, pc); % quadratic costs
% optimise
[pi,L,V] = lqr_fh(model.A,model.B,pc.QT,pc.Q,pc.R,ps);
% run controller on plant
[x,u] = simulate_feedback_time_indexed(x0,f,pi,ps);
% evaluate cost of trajectory on plant
cost = evaluate_trajectory_cost_fh(x,u,l,ps);
fprintf(1,'Cost (evaluated on plant) = %f\n',cost)
% plot
fn=1;figure(fn),clf
plot_lq_fh(fn,'LQR-FH',t,x,u,L,[],'g');