Description of test_lqr_ih
Home > examples > test_lqr_ih.m
test_lqr_ih
PURPOSE
Demo script: Test numerical solution of infinite horizon linear-quadratic regulator problem in continuous time.
SYNOPSIS
This is a script file.
DESCRIPTION
 Demo script: Test numerical solution of infinite horizon linear-quadratic regulator problem in continuous time.
CROSS-REFERENCE INFORMATION
This function calls:
l_quadratic Finite horizon quadratic cost function.
f_linear Linear dynamics function.
f_linear Linear dynamics function.
model_linear Simple linear model, with two state dimensions, one control dimension.
model_linear Simple linear model, with two state dimensions, one control dimension.
lqr_ih Solve Riccati equation and compute optimal gains for infinite horizon linear-quadratic regulator problem in continuous time.
plot_lq_fh Function for plotting solutions to the finite horizon LQ problem from the demo scripts
simulate_feedback Simulate trajectory under closed-loop feedback control
evaluate_trajectory_cost_ih Function for evaluating the cost along a trajectory under a given cost function - infinite horizon case
This function is called by:
SOURCE CODE
% Demo script: Test numerical solution of infinite horizon linear-quadratic regulator problem in continuous time.
clear all;
% set up numerical simulation
dt = 0.02;       % time step
N  = 200;        % number of time steps
t  = (0:N-1)*dt; % sample times
% simulation parameters
ps = []; ps.N = N; ps.dt = dt; ps.solver = 'euler';
% start state
x0 = [1;0];
% dynamics
model = model_linear; %
f = @(x, u) f_linear (x, u, model);
% cost
pc = [];
% state cost
pc.Q  = [1  0;  0  0.1];
% command cost
pc.R  = .1;
l  = @(x,u) l_quadratic (x, u, pc); % quadratic costs
% optimise
[pi,L,V] = lqr_ih(model.A,model.B,pc.Q,pc.R);
% run controller on plant
[x,u] = simulate_feedback(x0,f,pi,ps);
% evaluate cost of trajectory on plant
cost = evaluate_trajectory_cost_ih(x,u,l,ps);
fprintf(1,'Cost (evaluated on plant) = %f\n',cost)
% plot
fn=1;figure(fn),clf
plot_lq_fh(fn,'LQR',t,x,u,[],[],'g');