Description of test_lqr_fh_d
Home > examples > test_lqr_fh_d.m
test_lqr_fh_d
PURPOSE
Demo script: Test numerical solution of finite horizon linear-quadratic regulator problem in discrete time.
SYNOPSIS
This is a script file.
DESCRIPTION
 Demo script: Test numerical solution of finite horizon linear-quadratic regulator problem in discrete time.
CROSS-REFERENCE INFORMATION
This function calls:
l_quadratic_fh Finite horizon quadratic cost function.
f_linear_d Linear dynamics function in discrete time
f_linear_d Linear dynamics function in discrete time
lqr_fh_d Solve discrete Riccati equation and compute optimal gains for finite horizon LQR problem.
plot_lq_fh Function for plotting solutions to the finite horizon LQ problem from the demo scripts
simulate_feedback_time_indexed_d Simulate trajectory using Euler integration under closed-loop, time-indexed policy control, in continuous time
evaluate_trajectory_cost_fh_d Function for evaluating the cost along a trajectory under a given cost function
This function is called by:
SOURCE CODE
% Demo script: Test numerical solution of finite horizon linear-quadratic regulator problem in discrete time.
clear all;
% set up numerical simulation
dt = 0.02;       % time step
N  = 200;        % number of time steps
t  = (0:N-1)*dt; % sample times
% simulation parameters
ps = []; ps.N = N;
% start state
x0 = [1;0];
% dynamics
model.A = [ 1 dt ; ...
            0  1 ];
model.B = [ 0 ; ...
           dt ];
f = @(x, u) f_linear_d (x, u, model);         % linear dynamics (discrete time)
% cost
pc = [];
% terminal state cost
pc.QT = [1  0;  0  0.1];
% state cost
pc.Q  = dt*pc.QT;
% command cost
pc.R  = dt*.1;
l  = @(x,u,t) l_quadratic_fh (x, u, t, pc); % quadratic costs
% optimise
[pi,L,V] = lqr_fh_d(model.A,model.B,pc.QT,pc.Q,pc.R,ps);
% run controller on plant
[x,u] = simulate_feedback_time_indexed_d(x0,f,pi,ps);
% evaluate cost of trajectory on plant
cost = evaluate_trajectory_cost_fh_d(x,u,l,ps);
fprintf(1,'Cost (evaluated on plant) = %f\n',cost)
% plot
fn=1;figure(fn),clf
plot_lq_fh(fn,'LQR-FH (discrete time)',t,x,u,L,[],'r');