Description of evaluate_trajectory_cost_ih_d
Home > value > evaluate_trajectory_cost_ih_d.m
evaluate_trajectory_cost_ih_d
PURPOSE
Function for evaluating the cost along a trajectory under a given cost function in discrete time
SYNOPSIS
function cost = evaluate_trajectory_cost_ih_d (x, u, l, gamma)
DESCRIPTION
 Function for evaluating the cost along a trajectory under a given cost function in discrete time
 in:
     x     - matrix containing trajectory through state space
     u     - matrix containing trajectory of commands
     l     - function handle to cost function (in discrete time)
     gamma - discount factor
 out:
     cost   - (discounted) cost incurred
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
test_lqr_ih_d Demo script: Test numerical solution of infinite horizon linear-quadratic regulator problem in discrete time.
test_lspi_gridworld Demo script: Test LSPI solution of infinite horizon gridworld problem.
test_lspi_lqr_ih_d Demo script: Test LSPI solution of infinite horizon linear-quadratic regulator problem in discrete time.
test_lwlspi_lqr_ih_d Demo script: Test LWLSPI solution of infinite horizon linear-quadratic regulator problem in discrete time.
SOURCE CODE
% Function for evaluating the cost along a trajectory under a given cost function in discrete time
%
% in:
%     x     - matrix containing trajectory through state space
%     u     - matrix containing trajectory of commands
%     l     - function handle to cost function (in discrete time)
%     gamma - discount factor
%
% out:
%     cost   - (discounted) cost incurred
%
function cost = evaluate_trajectory_cost_ih_d (x, u, l, gamma)
if nargin<4
   error 'Too few parameters given'
end
[n ,N ] = size(u);
[n2,N1] = size(x);
if N1~=N+1
   error 'Bad dimensionality of x and u'
end
cost = sum((gamma.^(0:N-1)).*l(x(:,1:N),u));