Description of evaluate_trajectory_cost_fh
Home > value > evaluate_trajectory_cost_fh.m
evaluate_trajectory_cost_fh
PURPOSE
Function for evaluating the cost along a trajectory under a given cost function
SYNOPSIS
function cost = evaluate_trajectory_cost_fh (x, u, l, p)
DESCRIPTION
 Function for evaluating the cost along a trajectory under a given cost function
 in:
     x     - matrix containing trajectory through state space
     u     - matrix containing trajectory of commands
     l     - function handle to cost function
     p     - simulation struct
 out:
     cost   - cost incurred
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
test_ilqr_kawato_1dof_reach Demo script: Test ilqr on reaching problem for 2-muscle, 1-joint system with 'kawato model' muscle dynamics.
test_ilqr_kawato_arm Demo script: Test ilqr on reaching problem for 6-muscle, 2-joint system with 'kawato model' muscle dynamics.
test_ilqr_kawato_arm_reach Demo script: Test ilqr on reaching problem for 6-muscle, 2-joint system with 'kawato model' muscle dynamics.
test_ilqr_lqr_fh Demo script: Test solution of finite horizon linear-quadratic regulator problem in continuous time using ILQR.
test_ilqr_maccepa_reach Demo script: Test ilqr on reaching problem for MACCEPA actuator.
test_lqr_fh Demo script: Test numerical solution of finite horizon linear-quadratic regulator problem in continuous time.
ilqr Function for solving (finite horizon) optimal control problems with the Iterative Linear Quadratic Regulator method.
Test_ilqr_maccepa_contact_task Demo script: Test ilqr on reaching problem for MACCEPA actuator.
Test_ilqr_maccepa_contact_task Demo script: Test ilqr on reaching problem for MACCEPA actuator.
test_ilqr_maccepa_reach Demo script: Test ilqr on reaching problem for MACCEPA actuator.
SOURCE CODE
% Function for evaluating the cost along a trajectory under a given cost function
%
% in:
%     x     - matrix containing trajectory through state space
%     u     - matrix containing trajectory of commands
%     l     - function handle to cost function
%     p     - simulation struct
%
% out:
%     cost   - cost incurred
%
function cost = evaluate_trajectory_cost_fh (x, u, l, p)
if nargin<4
   error 'Too few parameters given'
end
[n ,N ] = size(u);
[n2,N1] = size(x);
if N1~=N+1
   error 'Bad dimensionality of x and u'
end
dt = p.dt;
t  = (0:N)*dt;
% integrate running cost & add final cost
cost = dt*sum(l(x(:,1:end-1),u,t)) + l(x(:,end),nan,nan);