Description of l_quadratic
Home > cost > l_quadratic.m
l_quadratic
PURPOSE
Finite horizon quadratic cost function.
SYNOPSIS
function l = l_quadratic (x, u, p)
DESCRIPTION
 Finite horizon quadratic cost function.
     J = \int_0^\infty x^T Q x + u^T R u dt
 in:
    x - state
    u - command
    p - parameter struct, containing
     .Q,R  - cost parameters
 out:
    l - cost
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
test_lqr_ih Demo script: Test numerical solution of infinite horizon linear-quadratic regulator problem in continuous time.
test_lqr_ih_d Demo script: Test numerical solution of infinite horizon linear-quadratic regulator problem in discrete time.
test_lspi_lqr_ih_d Demo script: Test LSPI solution of infinite horizon linear-quadratic regulator problem in discrete time.
test_lwlspi_lqr_ih_d Demo script: Test LWLSPI solution of infinite horizon linear-quadratic regulator problem in discrete time.
SOURCE CODE
% Finite horizon quadratic cost function.
%
%     J = \int_0^\infty x^T Q x + u^T R u dt
%
% in:
%    x - state
%    u - command
%    p - parameter struct, containing
%     .Q,R  - cost parameters
%
% out:
%    l - cost
%
function l = l_quadratic (x, u, p)
Q  = p.Q;
R  = p.R;
l=sum(x.*(Q*x))+sum(u.*(R*u),1);