Description of pi_ilqr
Home > control > pi_ilqr.m
pi_ilqr
PURPOSE
ILQR/G policy
SYNOPSIS
function u = pi_ilqr (x, t, p)
DESCRIPTION
 ILQR/G policy
 u = u0 + L (x-x0).
 in:
     x    - state
     t    - time step index
     p    - paramter struct, containing
      .un - nominal command
      .xn - nominal state
      .Ln - gains
 out:
     u  - action
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
test_ilqr_kawato_1dof_reach Demo script: Test ilqr on reaching problem for 2-muscle, 1-joint system with 'kawato model' muscle dynamics.
test_ilqr_kawato_arm Demo script: Test ilqr on reaching problem for 6-muscle, 2-joint system with 'kawato model' muscle dynamics.
test_ilqr_kawato_arm_reach Demo script: Test ilqr on reaching problem for 6-muscle, 2-joint system with 'kawato model' muscle dynamics.
test_ilqr_lqr_fh Demo script: Test solution of finite horizon linear-quadratic regulator problem in continuous time using ILQR.
test_ilqr_maccepa_reach Demo script: Test ilqr on reaching problem for MACCEPA actuator.
Test_ilqr_maccepa_contact_task Demo script: Test ilqr on reaching problem for MACCEPA actuator.
maccepavd_reach_p1 % Optimization problem 1: variable damping
maccepavd_reach_p2 % Optimization problem 1: fixed damping
test_ilqr_maccepa_reach_d3 Demo script: Test ilqr on reaching problem for MACCEPA actuator with U dimension of 3.
SOURCE CODE
% ILQR/G policy
%
% u = u0 + L (x-x0).
%
% in:
%     x    - state
%     t    - time step index
%     p    - paramter struct, containing
%      .un - nominal command
%      .xn - nominal state
%      .Ln - gains
%
% out:
%     u  - action
%
function u = pi_ilqr (x, t, p)
un = p.un;
xn = p.xn;
Ln = p.Ln;
u = un(:,t) + Ln(:,:,t)*(x-xn(:,t));